### ISSUE TITLE
R package for reading in images

### ISSUE THREAD

**Issue by drjwbaker** [mdlincoln/PastecR#3]
Hey. What package do you use so that R can read images? I'm getting

> add_image(test1, 1, ops)
> Error: file.exists(image_path) is not TRUE

Even though 

> file.exists("test.jpg")
> [1] TRUE

I think the error is with R being able to read in images rather than your code!

**Comment by mdlincoln** [comment]
Well, PastecR doesn't actually read the image file in - it just creates an http call to the Pastec server which passes the raw data from the image.

The sample code you provide doesn't show what value you've assigned to the variable `test1` - could you post the rest?

**Comment by drjwbaker** [comment]
> test1 <- system.file("img", "/home/pi3/Pictures/emb/1800/test.jpg", package = "PastecR")

Maybe I'm not using `system.file()` correctly..

**Comment by drjwbaker** [comment]
![pastecr](https://cloud.githubusercontent.com/assets/4965300/17431029/a5cc3ae4-5aef-11e6-8816-18cfac085b7e.png)

**Comment by drjwbaker** [comment]
![pastecr](https://cloud.githubusercontent.com/assets/4965300/17431061/d0dc00b6-5aef-11e6-9067-8c677ac3e1e2.png)

**Comment by mdlincoln** [comment]
Yeah,`system.file` is usually only used to access files that are installed with a package. You just need to supply the file path as a character vector:

```
test1 <- "/home/is boxes/..."
add_image(test1, 1, ops)
```

I _do_ need to add a little fix so that the error message correctly tells you which path you _tried_ to access however.

**Comment by drjwbaker** [comment]
Okay. Setting up R with 'files that are installed with a package' is not something I know how to do. But from what you are saying, changing my second line to:

> test1 <- "/home/osboxes/Pictures/1800/test1.jpg"

Will load it in fine.

My next question then is, does PastecR support some way of loading in large numbers of files (I have about 38k I want - eventually - to run this across)?

**Comment by drjwbaker** [comment]
So it worked. But the image I wanted to test with is too small (throwing the Pastec error listed at http://pastec.io/doc/oss/). Which is super annoying!

**Comment by mdlincoln** [comment]
You can certainly do 38k files - I've done it with 200k.

**Comment by drjwbaker** [comment]
With apologies for reopening this, how then are you using the 

> add_image(erasmus1, 1, ops)
> add_image(erasmus2, 2, ops)
> add_image(erasmus3, 3, ops)
> add_image(nightwatch, 4, ops)

syntax to load in lots of images (that is, without doing in manually)? I presume `add_image` performs similar to some other commands in R?

**Comment by mdlincoln** [comment]
So if I had a directory of jpg images, for example, I'd collect all the image file paths in one character vector, and then use `mapply` to run `add_image` on each value of the vector.

``` r
# Get image file paths
img_paths <- dir("*.jpg")

# Generate a vector of image ids that is the same length as the vector of image paths
img_ids <- seq_along(img_paths)

# Pass the image paths and image ids into mlapply, which will run the specified 
# function once per pair of path/id values
mapply(function(x, y) add_image(x, y, ops), img_paths, img_ids)
```

**Comment by drjwbaker** [comment]
Huh. That looks good. I need to work on my R foobar :)

**Comment by mdlincoln** [comment]
😄 you could do exactly the same thing with a `for` loop, but i'm such an R convert now I almost always use the `*apply` functions instead (or the even more useful [purrr](https://github.com/hadley/purrr) functions! But one step at a time 👍 )
